config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  post '/', to: 'products#index'
  resources :products do
    member do
      put :add_to_cart
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      get :payment
      post :transaction
    end
  end

  resource :cart, only: [:show, :destroy]
  get '/checkout', to: 'carts#checkout'

  # API
  namespace :api do
    namespace :v2 do
      resources :candidates, only: [:index, :show]
    end
  end

  resources :candidates do
    member do
      put :vote
      get :log
    end
  end

  root 'candidates#index'
end

app/views/shared/frontend/_flash.html.erb
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "iVoting", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "候選人列表", candidates_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "商品列表", products_path, class: 'nav-link' %>
      </li>
    </ul>

    <ul class="navbar-nav">

      <li class="nav-item">
        <%= link_to "購物車(#{current_cart.items.count})", cart_path, class: 'nav-link' if current_cart.present? %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "我的訂單", orders_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to edit_user_registration_path, class: 'nav-link' do %>
            <%= avatar_tag(current_user, size: '100x100', class_name: 'avatar nav-avatar') %> 個人資料
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "登出", destroy_user_session_path, class: 'nav-link', method: 'delete' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "註冊", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "登入", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>