config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  post '/', to: 'products#index'
  resources :products do
    member do
      put :add_to_cart
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      get :payment
      post :transaction
    end
  end

  resource :cart, only: [:show, :destroy]
  get '/checkout', to: 'carts#checkout'

  # API
  namespace :api do
    namespace :v2 do
      resources :candidates, only: [:index, :show]
    end
  end

  resources :candidates do
    member do
      put :vote
      get :log
    end
  end

  root 'candidates#index'
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  paginates_per 10
  has_many :vote_logs
  has_many :users, through: :vote_logs
  has_one :signature
  accepts_nested_attributes_for :signature

  validates :name, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 40 }

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end
end

app/controllers/api/v2/candidates_controller.rb
class Api::V2::CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end

  def show
    @candidate = Candidate.find_by(id: params[:id])
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote, :log]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @candidates = Candidate.order(vote: :desc).page(params[:page])
  end

  def show
  end

  def new
    @candidate = Candidate.new
    authorize @candidate
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to root_path, notice: "新增候選人成功!"
    else
      render :new
    end
  end

  def edit
    authorize @candidate
    @candidate.build_signature if @candidate.signature.nil?
  end

  def update
    if @candidate.update(candidate_params)
      redirect_to root_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    authorize @candidate
    @candidate.destroy
    redirect_to root_path, notice: "資料刪除成功!"
  end

  def vote
    if user_signed_in?

      log = current_user.vote_logs.new(candidate: @candidate,
                                       ip_address: request.remote_ip)

      if log.save
        message = "投票成功"
      else
        message = log.errors.full_messages.first
      end

      redirect_to root_path, notice: message
    else
      redirect_to root_path, notice: '請先登入會員!'
    end
  end

  def log
    @users = @candidate.users
  end

  private
  def find_candidate
    @candidate = Candidate.find(params[:id])
  end

  # Strong Parameters
  def candidate_params
    params.require(:candidate).permit(
      :name,
      :age,
      :policy,
      :party,
      :degree,
      signature_attributes: [:id, :content, :active]
    )
  end
end

app/views/candidates/_form.html.erb
<%= simple_form_for(candidate) do |form| %>
  <div class="box">
    <%= form.input :name, label: '姓名' %>
    <%= form.input :degree, label: '學歷' %>
    <%= form.input :party, label: '政黨' %>
    <%= form.input :age, label: '年紀' %>
    <%= form.input :policy, label: '政見' %>

    <hr>
    <%= form.simple_fields_for :signature do |signature_form| %>
      <%= signature_form.input :content, label: '簽名檔' %>
    <% end %>

    <%= form.submit class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= paginate @candidates, theme: 'twitter-bootstrap-4' %>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th>投票</th>
      <th>得票數</th>
      <th>候選人</th>
      <th>處理</th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td>
        <%= link_to "投票！", vote_candidate_path(candidate), class: 'btn btn-sm btn-warning', method: 'put', data: { confirm: '確認投票?!'} %>
      </td>
      <td>
        <%= link_to "#{candidate.vote_logs_count} 票", log_candidate_path(candidate) %>
      </td>
      <td>
          <%= link_to candidate.name, candidate_path(candidate) %>
      </td>
      <td>
        <%= link_to "編輯", edit_candidate_path(candidate), class: 'btn btn-sm btn-success' %>
        <%= link_to "刪除", candidate_path(candidate), class: 'btn btn-sm btn-danger', method: 'delete', data: { confirm: '確定嗎?!'} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新增候選人', new_candidate_path, class: 'btn btn-primary btn-lg' if user_signed_in? && policy(@candidates).new? %>

app/views/candidates/log.html.erb
<h1>投票紀錄</h1>

<ul>
<% @users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</ul>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<% if @candidate.errors.any? %>
  <ul>
  <% @candidate.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(@candidate) do |form| %>
  <div class="box">
    <div class="candidate_field">
      <%= form.label :name, '姓名' %>
      <%= form.text_field :name %>
    </div>

    <div class="candidate_field">
      <%= form.label :party, '黨派' %>
      <%= form.text_field :party %>
    </div>

    <div class="candidate_field">
      <%= form.label :age, '年紀' %>
      <%= form.text_field :age %>
    </div>

    <div class="candidate_field">
      <%= form.label :policy, '政策' %>
      <%= form.text_area :policy %>
    </div>

    <%= form.submit class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

app/views/candidates/show.html.erb
<% if @candidate  %>
  <h1><%= @candidate.name %></h1>

  <ul>
    <li>得票數：<%= @candidate.vote %>票</li>
    <li>年紀：<%= @candidate.age %></li>
    <li>學歷：<%= @candidate.degree %></li>
    <li>黨派：<%= @candidate.party %></li>
    <li>政見：<%= @candidate.policy %></li>
  </ul>
<% else %>
  <h1>沒有這個人</h1>
<% end %>