config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  post '/', to: 'products#index'
  resources :products do
    member do
      put :add_to_cart
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      get :payment
      post :transaction
    end
  end

  resource :cart, only: [:show, :destroy]
  get '/checkout', to: 'carts#checkout'

  # API
  namespace :api do
    namespace :v2 do
      resources :candidates, only: [:index, :show]
    end
  end

  resources :candidates do
    member do
      put :vote
      get :log
    end
  end

  root 'candidates#index'
end

app/models/cart.rb
class Cart
  include Taxable
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def empty?
    @items.empty?
  end

  def present?
    !empty?
  end

  def add_item(product_id)
    found_item = @items.find { |i| i.product_id == product_id }

    if found_item
      found_item.increment(1)
    else
      @items << CartItem.new(product_id)
    end
  end

  def total_price
    total = @items.reduce(0) { |sum, item| sum + item.total_price }
    total = total * 0.9 if super_good_day?
    total
  end

  def serialize
    {
      "items" => @items.map do |i|
                   {"product_id" => i.product_id, "quantity" => i.quantity }
                 end
    }
  end

  def self.from_hash(hash = nil)
    if hash && hash["items"]
      new hash["items"].map { |i| CartItem.new(i["product_id"], i["quantity"]) }
    else
      new
    end
  end

  private
  def xmas?
    #....
    Time.now.day == 25 && Time.now.month == 12
  end

  def super_good_day?
    Time.now.day == 10 && Time.now.month == 2
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_login, only: [:checkout]

  def show
  end

  def destroy
    session[:cart9527] = nil
    redirect_to products_path, notice: '購物車已清空'
  end

  def checkout
    @order = current_user.orders.build
  end

  private
  def check_login
    redirect_to new_user_session_path, notice: '請先登入會員' unless user_signed_in?
  end
end

app/views/carts/_cart.html.erb
<table class="table">
  <thead>
    <tr>
      <th>商品名稱</th>
      <th>數量</th>
      <th>單價</th>
      <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% current_cart.items.each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.quantity %></td>
      <td><%= item.product.price %></td>
      <td><%= item.total_price %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">總價</td>
      <td><%= current_cart.total_price %></td>
    </tr>
  </tfoot>
</table>

app/views/carts/checkout.html.erb
<h1>結帳</h1>

<%= render 'carts/cart' %>

<%= simple_form_for(@order) do |form| %>
  <%= form.input :recipient %>
  <%= form.input :phone %>
  <%= form.input :address %>
  <%= form.input :note %>

  <%= form.submit '建立訂單', class: 'btn btn-success btn-lg' %>
<% end %>

app/views/carts/show.html.erb
<h1>購物車 <%= link_to "清空購物車", cart_path, method: 'delete', class: 'btn btn-sm btn-danger', data: {confirm: '確認清空購物車?!'} %></h1>

<%= render 'carts/cart' %>

<%= link_to "繼續選購", products_path, class: 'btn btn-success btn-lg' %>
<%= link_to "結帳", checkout_path, class: 'btn btn-danger btn-lg' %>