config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  post '/', to: 'products#index'
  resources :products do
    member do
      put :add_to_cart
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      get :payment
      post :transaction
    end
  end

  resource :cart, only: [:show, :destroy]
  get '/checkout', to: 'carts#checkout'

  # API
  namespace :api do
    namespace :v2 do
      resources :candidates, only: [:index, :show]
    end
  end

  resources :candidates do
    member do
      put :vote
      get :log
    end
  end

  root 'candidates#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :skus
  accepts_nested_attributes_for :skus, allow_destroy: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :add_to_cart, :edit, :update]

  def index
    @products = Product.all
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: '商品更新完成'
    else
      render :edit
    end
  end

  def add_to_cart
    current_cart.add_item(@product.id)
    session[:cart9527] = current_cart.serialize

    redirect_to products_path, notice: '已加入購物車'
  end

  private
  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name,
      :price,
      :description,
      :is_available,
      skus_attributes: [:id, :spec, :quantity, :_destroy]
    )
  end
end

app/views/products/_form.html.erb
<%= simple_form_for(product) do |form| %>
  <%= form.input :name %>
  <%= form.input :price %>
  <%= form.input :description %>
  <%= form.input :is_available %>
  <hr>
  <h2>
    庫存
  </h2>
  <%= form.simple_fields_for :skus do |sku_form| %>
    <%= render 'sku_fields', f: sku_form %>
  <% end %>
  <div class="links">
    <%= link_to_add_association "新增庫存", form, :skus, class: 'btn btn-sm btn-danger' %>
  </div>
  <hr>
  <%= form.submit class: 'btn btn-success' %>
<% end %>

app/views/products/_sku_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-8">
      <%= f.input :spec, label: false, placeholder: '規格：XL、L、大、中、小' %>
    </div>
    <div class="col-3">
      <%= f.input :quantity, label: false, placeholder: '數量' %>
    </div>
    <div class="col-1">
      <%= link_to_remove_association "X", f, class: 'btn btn-sm btn-danger' %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>更新商品</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1>商品列表</h1>

<ul>
  <% @products.each do |product| %>
  <li>
    <%= link_to product.name, product %> | <%= product.price %>元
    <%= link_to "加入購物車", add_to_cart_product_path(product), class: 'btn btn-danger btn-sm', method: 'put' %>
    <%= link_to "編輯", edit_product_path(product), class: 'btn btn-success btn-sm' %>
  </li>
  <% end %>
</ul>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>